# Description: SMS API
# Starts RabbitMQ, JasminSMS and ECNSMSAPI

# To run...
# docker-compose -f smsapi.development.yml up
#
# To tear down and clean up
# docker-compose -f smsapi.development.yml down

version: '2'
services:

     rabbitmq:
        image: rabbitmq:3.6.9-management-alpine
        ports:
        - "5671:5671"
        - "5672:5672"
        - "4369:4369"
        - "15671:15671"
        - "15672:15672"
        - "25672:25672"
        networks:
        - smsnetwork

networks:
    smsnetwork:
        driver: bridge

# docker run -d -p 5671:5671 -p 5672:5672 -p 4369:4369 -p 15671:15671 -p 15001:15672 -p 25672:25672 --name rabbitmq --network=smsnetwork rabbitmq:3.6.6-management
# docker run -d -p 5000:5000 -v C:\projects\dockerdirectory\ecnsmsapi\logs:/app/logs --name ecnsmsapi --network=smsnetwork ecn780/ecnsmsapi
# docker run -d -p 1401:1401 -p 2775:2775 -p 8990:8990 -v c:\projects\dockerdirectory\jasminsms\logs:/var/log/jasmin --name jasminsms --network=smsnetwork ecn780/jasminsms